#!/usr/bin/env bash

# Bash script to transfer a file from our client to a server

# Variables
yellow='\e[0;33m'
reset='\033[0m'
file="$1"
ip="$2"
user="$3"
key="$4"

# Check if 4 parameters are passed
if [ $# -eq 4 ]; then
    # Transfer file to server
    scp -i "$key" -o StrictHostKeyChecking=no "$file" "$user"@"$ip":~/    
else
    # Display usage message
    echo -e "Usage: ${yellow}$(basename "$0") PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
fi

