#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server
apt-get -y update
apt-get -y install haproxy=1.5

sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
echo -e "\nfrontend localnodes\n\tbind *:80\n\tmode: http\n\tdefault_backend nodes\n\n\nbackend nodes\n\tbalance roundrobin\n\tserver 136122-web-01 100.25.212.212:80 check\n\tserver 136122-web-02 52.3.220.157:80 check\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
