#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server
apt-get -y update
apt-get -y upgrade

# Install HAproxy
apt-get -y install haproxy

# Configure HAproxy
config="\
frontend balancer
    bind *:80
    mode http
    default_backend lb-backends
backend lb-backends
    balance roundrobin
    server web-01 136122-web-01 100.25.212.212:80 check
    server web-02 136122-web-02 52.3.220.157:80 check
"
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$config" >> /etc/haproxy/haproxy.cfg

# Restart HAproxy to apply changes
service haproxy restart
